### ISSUE TITLE
Add Stricter logic to forms

### ISSUE THREAD

**Issue by chenhoward** [calblueprint/phc#9]
Add stricter formatting and logic to forms to make sure we have valid data.  What specifically?  I'm not sure yet but in the next meeting we can discuss what this would be.  @Byronium any that you were specifically missing?

**Comment by Byronium** [comment]
make sure that birthdays, SSNs, and phone number are in proper format. this is important because these are all fields that may be used to search up the user in the future. currently, there's a surprising number of 7 or 8 digit SSNs in the database, which are of course impossible. 
note that the user should not be REQUIRED to enter birthday, SSN, and phone number but if they DO enter numbers in, those numbers should be correct.

**Comment by sxnahm** [comment]
Bryon,

Actually, some participants refuse to give their full SSN, and only give the last four digits. This can still be useful for associating the participant with an earlier visit.  I recommend accepting SSN fragments.

Steve Nahm

**Comment by chenhoward** [comment]
Agreed ^ that happens alot

**Comment by Byronium** [comment]
@warrenshen bump

**Comment by Byronium** [comment]
could you get on this warren? a lot of entries from the last event are causing trouble because they weren't formatted correctly (for example, birthdates should have been validated as YYYY-MM-DD, but we have entires like 65-1-1 instead of 1965-01-01)

**Comment by Byronium** [comment]
nvm warren @twuster wants to handle this.

**Comment by warrenshen** [comment]
Thanks @twuster !
